config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get '/users/auth/:provider/callback', to: 'sessions#create'

  root 'welcome#index', as: 'root'

  get 'welcome/home', as: 'welcome'

  get 'tasks/by_date', as: 'by_date'

  post '/tasks/complete', as: 'complete'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :goals do
    resources :tasks
  end

  resources :tasks

  resources :categories, only: [:show, :index, :create]

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :goals
  belongs_to :user

  def goal_by_category
    Goal.all.select do |goal|
      if self.goal_id == goal.id
        goal
      end
    end
  end

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  has_many :categories
  has_many :tasks
  belongs_to :user
  accepts_nested_attributes_for :categories

  validates :title, presence: true
  validates :description, presence: true

  def categories_attributes=(category_attributes)
    category_attributes.values.each do |category_attribute|
      if category_attribute != {"name"=>""}
        category = Category.find_or_create_by(category_attribute)
        self.categories << category
      end
    end
  end

  def uncompleted_tasks
    self.tasks.select do |task|
      if !task.completed && task.due_date >= Date.today
        task
      end
    end
  end

  def past_due
    self.tasks.select do |task|
      if task.due_date < Date.today
        task
      end
    end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :goal
  has_many :users, :through=> :goals

  validates :description, presence: true
  validates :due_date, presence: true

  scope :by_date, -> { order(due_date: :asc).where(completed: false) }

  def completed?
    self.completed ? "Completed. You're Awesome!" : "Not Yet Completed"
  end

  def upcoming_deadlines
    self.select do |task|
      if task.due_date <= Date.today + 7 && task.due_date >= Date.today
        task
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :goals
  has_many :categories, through: :goals
  has_many :tasks, through: :goals

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :omniauthable, :omniauth_providers => [:github]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery :except => [:callback]

  def after_sign_in_path_for(resource_or_scope)
   welcome_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @goals = @category.goal_by_category
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  def index
    @goals = current_user.goals
    respond_to do |f|
      f.html { render :index, status: 200 }
      f.json { render json: @goals, status: 200 }
    end
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.create(goal_params.merge(user_id: current_user.id))
    render json: @goal, status: 200
  end

  def show
    @uncompleted_tasks = @goal.uncompleted_tasks
    @past_due = @goal.past_due
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @goal, status: 200 }
    end
  end

  def edit
  end

  def update
    @goal.update(goal_params)
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @goal, status: 200 }
    end
  end

  def destroy
    @goal.delete
    respond_to do |f|
      f.html { render :index }
      f.json { render json: @goal }
    end
  end

  private

  def set_goal
    @goal = Goal.find(params[:id])
  end

  def goal_params
    params.require(:goal).permit(:title, :description, category_ids:[], categories_attributes: [:id, :name])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_by(uid: auth['uid'])
    session[:user_id] = @user.id
    render 'welcome/home'
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @goal = Goal.find(params[:goal_id])
  end

  def new
    @task = Task.new(goal_id: params[:goal_id])
  end

  def create
    @task = Task.create(task_params.merge(user_id: current_user.id))

    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      redirect_to new_task_path, notice: 'Please try again. Be sure to fill in all fields.'
    end
  end

  def show
  end

  def edit
  end

  def update
    @task.update(task_params)

    if @task.save
      redirect_to task_path(@task), notice: 'Task was successfully updated.'
    else
      redirect_to edit_task_path(@task), notice: 'Be sure not to leave any fields blank.'
    end
  end

  def destroy
    @task.delete
    redirect_to goal_path(@task.goal_id), notice: 'Task was successfully deleted.'
  end

  def complete
    task = Task.find(params[:id])
    task.update(:completed => true)
    redirect_to task_path(task)
  end

  private
  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:description, :due_date, :completed, :goal_id, :user_id, :id)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    render :layout => false
  end

  def home
    if current_user
      render :home
    else
      redirect_to root_path, notice: 'You must be logged in to view that page.'
    end
  end

end

app/views/categories/show.html.erb
<h1> <%= @category.name %> Goals </h1>

<% @goals.each do |goal| %>
  <%= link_to goal.title, goal_path(goal) %>
<% end %>

app/views/goals/_form.html.erb
<%= form_for @goal do |f| %>

<p><%= f.label :title %></p>
<%= f.text_field :title %><br/>

<p><%= f.label :description %></p>
<%= f.text_area :description, size: "24x6" %><br/>
<% if !Category.all.empty? %>
<p><%= f.label "Choose Existing Category" %></p>
<%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
<% end %>
<%= f.fields_for :categories, @goal.categories.build do |category_fields| %>
<p><%= f.label "Choose New Category" %></p>
     <%= category_fields.text_field :name %>
 <% end %></p>
<%= f.submit %>
<% end %>

<div id="goalResult">
  <h1 id="goalHeading"></h1>
  <h2 id="goalTitle"></h2>
  <p id="goalDescription"></p>
  <p id="category"></p>
</div>

app/views/goals/edit.html.erb
<h2> Edit Goal </h2>
<%= form_for(@goal, :url => {:action => 'update', :id => @goal.id}, :html => {:id => 'goal_form'}) do |f| %>
<%= render(:partial => "form", :locals => {:f => f}) %>
<% end %>

app/views/goals/index.html.erb
<h2>Goals</h2>
<ol>
<% @goals.each do |goal| %>
  <h3 ><%= goal.id %>: <%= link_to goal.title, goal_path(goal) %></h3>
  <div id="body-<%= goal.id %>"><%= truncate goal.description %></div>
  <button class="js-more" data-id="<%= goal.id %>">More...</button><br>
<% end %>
</ol>
<p><%=  link_to "Create New Goal", new_goal_path%></p>

app/views/goals/new.html.erb
<div id="newGoal"><h1 id="pageHeading">Enter New Goal</h1></div>
<%= form_for(@goal, :url => {:action => 'create'}, :html => {:id => 'goal_form'}) do |f| %>
<%= render(:partial => "form", :locals => {:f => f}) %>
<% end %>

app/views/goals/show.html.erb
<h1 class="goalTitle"><%= @goal.title %></h1>
<p class="goalDescription"><%= @goal.description %></p>

<h4>Categories:</h4>
<ul>
 <% @goal.categories.each do |category| %>
    <li class="goalDescription"><%= category.name %> </li>
<% end %>
</ul>

<a href="#" class="js-next" data-id="<%=@goal.id%>">Next...</a><br>
<p><%=link_to "Add Another Goal", new_goal_path  %></p>
<p><%= link_to "Add Task", new_goal_task_path(@goal) %></p>
<p><a href="#" class="js-edit" data-id="<%=@goal.id%>">Edit Goal</a></p>
<p><button class="js-delete" data-id="<%= @goal.id %>">Delete Goal</button></p>

app/views/layouts/_header.html.erb
<% if flash[:notice] %>
    <%= flash[:notice] %></p>
<% end %>

Goal Tracker
 <%= link_to "Home", welcome_path %> | <%= link_to "View Goals", goals_path %>
| <%= link_to "Sign out", destroy_user_session_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>

<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>

<%= f.hidden_field :goal_id %>

<p><%= f.label :description %></p>
<%= f.text_field :description %><br/>

<p><%= f.label :due_date %></p>
<%= f.date_field :due_date %><br/>

<p><%= f.label "Completed?" %>
<%= f.check_box :completed %></p>

<%= f.submit %>
<% end %>

app/views/tasks/by_date.html.erb
<ul>
<% Task.by_date.each do |task| %>
<li><%= task.description %>
  <p> Due: <%=task.due_date.strftime("%A, %b %d, %Y") %> </p>
</li>
<% end %>
</ul>

app/views/tasks/edit.html.erb
<h2> Edit Task </h2>
<%= form_for(@task, :url => {:action => 'update', :id => @task.id}) do |f| %>
<%= render(:partial => "form", :locals => {:f => f}) %>
<% end %>

app/views/tasks/index.html.erb
<h1> <%= @goal.title %> Tasks </h1>

<% @goal.tasks.each do |task| %>
<%= link_to task.description, task_path(task) %>
<% end %>

app/views/tasks/new.html.erb
<h1>Enter New Task</h1>

<%= form_for(@task, :url => {:action => 'create'}) do |f| %>
<%= render(:partial => "form", :locals => {:f => f}) %>
<% end %>

app/views/tasks/show.html.erb
<h2> <%= @task.description %> </h2>
<p> Deadline: <%= @task.due_date.strftime("%b %d, %Y") %> </p>
<p> <%= @task.completed? %> </p>

<p><%= button_to "Mark Complete", {:controller => :tasks,
      :action => 'complete', :id => @task.id }, :method => :post %></p>

<p><%=link_to "Edit Task", edit_task_path  %></p>

<p><%= button_to "Delete Task", {:controller => :tasks,
      :action => 'destroy', :id => @task.id }, :method => :delete %></p>

<p><%= link_to "Return to Goal", goal_path(@task.goal_id) %></p>

app/views/welcome/home.html.erb
<h1>Welcome, <%= current_user.email %>!</h1>

 <p>View <%= link_to "Goals", goals_path%></p>

<p>Create New <%=  link_to "Goal", new_goal_path%></p>

<p>View <%= link_to "Tasks", by_date_path %></p>

<h3>Explore Goals by Category</h3>
<ul>
<% if !current_user.categories.empty? %>
  <% current_user.categories.each do |category| %>
  <% if category.name != "" %>
      <li> <%= link_to category.name, category_path(category) %> </li>
    <% end %>
  <% end %>
<% else %>
  You have no goals added right now
<% end %>
</ul>

<h3>Upcoming Deadlines</h3>
<ul>
<% if !current_user.tasks.empty? %>
  <% current_user.tasks.each do |task| %>
    <li> <%= link_to task.description, task_path(task) %> </li>
  <% end %>
<% else %>
  You have no upcoming deadlines
<% end %>

</ul>

app/views/welcome/index.html.erb
<% if flash[:notice] %>
    <%= flash[:notice] %></p>
<% end %>

<h1>Welcome to Goal Tracker</h1>
<%= link_to "Sign up with Email",  new_user_registration_path %> |
<%= link_to "Sign in with Email", new_user_session_path %> |
<%= link_to "Sign in or Create New Account with Github", '/users/auth/github' %>